### ISSUE TITLE
nvcc fatal   : redefinition of argument 'std'

### ISSUE THREAD

**Issue by navta** [XapaJIaMnu/gLM#3]
Hi,

I got this error when compiling (make).

"nvcc fatal   : redefinition of argument 'std'"

Do you have any idea what went wrong?

Thank you!

**Comment by XapaJIaMnu** [comment]
Could you leave more details? What are your OS/gcc/cuda/boost versions? Try `-DBAD_HOST` when runing cmake.

**Comment by navta** [comment]
Thank you for the reply.

OS:  4.9.13-gentoo
gcc: 4.9.4
cuda: 7.5
boost: 1.62.0

Tried -DBAD_HOST but same error.
During cmake it said "yaml-cpp not found on the system, not building fakeRNN", but I suppose this could be ignored.

**Comment by XapaJIaMnu** [comment]
Ye, the yaml-cpp error can be ignored safely.
I suspect it's related to some weird issue between the cuda version and the compiler version..
Is there any reason you are using CUDA 7.5 instead of 8 and GCC 4.9.X instead of 5?

Could you do `make VERBOSE=1` and copy/paste the nvcc command that fails?

**Comment by navta** [comment]
I don't have any privilege to update those versions.  

It stopped at the following command:

`/opt/cuda/bin/nvcc -M -D__CUDACC__ /home/navta/gLM/gpu/memory_management.cu -o /home/navta/gLM/release_build/gpu/CMakeFiles/memory_management.dir//memory_management_generated_memory_management.cu.o.NVCC-depend -ccbin /usr/bin/cc -m64 --std c++11 -Xcompiler ,\"-O3\",\"-Wall\",\"-DNDEBUG\",\"-g\" -lcudart -O3 -code=sm_37 -arch=compute_37 -std=c++11 -Xcompiler -D__CORRECT_ISO_CPP11_MATH_H_PROTO -DNVCC -I/opt/cuda/include -I/home/navta/gLM/Btree -I/home/navta/gLM/Trie -I/home/navta/gLM/Parser -I/home/navta/gLM/misc -I/home/navta/gLM/gpu -I/home/navta/gLM/LM
`
There are two "std" argument, if I remove the `--std c++11` I could proceed. So I comment out the following line in CMakeLists.txt:

```
#if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS 6.0)
#    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
#endif()
```

But then I got stopped on the following command:

```
/opt/cuda/bin/nvcc /home/navta/gLM/gpu/memory_management.cu -c -o /home/navta/gLM/release_build/gpu/CMakeFiles/memory_management.dir//./memory_management_generated_memory_management.cu.o -ccbin /usr/bin/cc -m64 -Xcompiler ,\"-O3\",\"-Wall\",\"-DNDEBUG\",\"-g\" -lcudart -O3 -code=sm_37 -arch=compute_37 -std=c++11 -Xcompiler -D__CORRECT_ISO_CPP11_MATH_H_PROTO -DNVCC -I/opt/cuda/include -I/home/navta/gLM/Btree -I/home/navta/gLM/Trie -I/home/navta/gLM/Parser -I/home/navta/gLM/misc -I/home/navta/gLM/gpu -I/home/navta/gLM/LM
/usr/include/string.h: 関数 ‘void* __mempcpy_inline(void*, const void*, size_t)’ 内:
/usr/include/string.h:652:42: エラー: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;

-- Removing /home/navta/gLM/release_build/gpu/CMakeFiles/memory_management.dir//./memory_management_generated_memory_management.cu.o
/usr/bin/cmake -E remove /home/navta/gLM/release_build/gpu/CMakeFiles/memory_management.dir//./memory_management_generated_memory_management.cu.o
CMake Error at memory_management_generated_memory_management.cu.o.cmake:282 (message):
  Error generating file
  /home/navta/gLM/release_build/gpu/CMakeFiles/memory_management.dir//./memory_management_generated_memory_management.cu.o

```

**Comment by XapaJIaMnu** [comment]
You can't remove --std c++11, because the codebase relies heavily on c++11 features.

Could you remove the c++11 bit from this line:
https://github.com/XapaJIaMnu/gLM/blob/master/gpu/CMakeLists.txt#L12
And try again? Leave all other files unchanged.
Also you could easily download a local copy of cuda 8 in your local working directory, extract it and then run cmake as
`CUDA_BIN_PATH=/path/to/cuda cmake ..`
Refer to this entry on [SO](https://stackoverflow.com/questions/19980412/how-to-let-cmake-find-cuda).

**Comment by navta** [comment]
removing c++11 from gpu/CMakeLists.txt#L12 gives similar result. Will try to get a local copy of cuda 8.

I tried on another machine with specs:
OS: Ubuntu 16.04
gcc: 5.4.0
cuda: 8.0
boost: 1.58.0
The problem I had were:
1. Couldn't find cuda sdk:
`Make Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find CUDA (missing: CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (found
  version "8.0")
`
Solved by adding "-D CUDA_TOOLKIT_ROOT_DIR=/path/to/cuda" to cmake
2. Couldn't find numpy:
`[ 96%] Building CXX object lib/CMakeFiles/ngrams_nematus.dir/python_bridge.cpp.o
In file included from /home/navta/gLM/lib/python_bridge.cpp:1:0:
/home/navta/gLM/gpu/nematus_ngrams.hh:7:33: fatal error: numpy/ndarrayobject.h: No such file or directory
`
Solved by setting  CPATH to the output of `python -c "import numpy as np; print np.get_include()"`. Refer to [this](https://github.com/ethereon/lycon/issues/1).

**Comment by XapaJIaMnu** [comment]
So, you managed to build it now on a recent ubuntu system?

I will add your workaround to 2) in CMakeLists.txt and I will add 1) to the README.

Let me know if newer CUDA version helps the original issue you had on the gentoo system.

**Comment by navta** [comment]
> So, you managed to build it now on a recent ubuntu system?

yes, I did.

> Let me know if newer CUDA version helps the original issue you had on the gentoo system.

Will do.

Thank you very much!
